// <auto-generated />
namespace attfire1_assignment2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ParentAndStudentClass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ParentAndStudentClass));
        
        string IMigrationMetadata.Id
        {
            get { return "201310030850292_ParentAndStudentClass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
